/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_menu;

import Halaman_Utama.Halaman_utama;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class login_username extends javax.swing.JFrame {

    /**
     * Creates new form login_username
     */
    public login_username() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_CloseUsername = new javax.swing.JButton();
        btn_MinimizeUsername = new javax.swing.JButton();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        btn_masukLoginRFID = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_CloseUsername.setOpaque(false);
        btn_CloseUsername.setContentAreaFilled(false);
        btn_CloseUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CloseUsernameMouseClicked(evt);
            }
        });
        btn_CloseUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CloseUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CloseUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 20, 20, 30));

        btn_MinimizeUsername.setOpaque(false); btn_MinimizeUsername.setContentAreaFilled(false);
        btn_MinimizeUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MinimizeUsernameMouseClicked(evt);
            }
        });
        btn_MinimizeUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MinimizeUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(btn_MinimizeUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 20, 20, 30));

        Username.setBackground(new java.awt.Color(244, 243, 243));
        Username.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        Username.setForeground(new java.awt.Color(102, 102, 102));
        Username.setBorder(null);
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 171, 180, 30));

        Password.setBackground(new java.awt.Color(244, 243, 243));
        Password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        Password.setForeground(new java.awt.Color(102, 102, 102));
        Password.setBorder(null);
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 228, 180, 27));

        login.setOpaque(false);
        login.setContentAreaFilled(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 90, 30));

        btn_masukLoginRFID.setOpaque(false); btn_masukLoginRFID.setContentAreaFilled(false);
        btn_masukLoginRFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masukLoginRFIDActionPerformed(evt);
            }
        });
        getContentPane().add(btn_masukLoginRFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 318, 150, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_menu/pictures/login_username.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CloseUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseUsernameMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_CloseUsernameMouseClicked

    private void btn_CloseUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CloseUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CloseUsernameActionPerformed

    private void btn_MinimizeUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizeUsernameMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_MinimizeUsernameMouseClicked

    private void btn_MinimizeUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MinimizeUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MinimizeUsernameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        try {
            // Connection Connect = (Connection) koneksi.getConDB();
            Username.requestFocus();
            java.sql.Connection conn = (Connection) connector_mysql.configDB();
            java.sql.Statement stat = conn.createStatement();
            ResultSet result = stat.executeQuery("select * from login_username where "
                    + "username='" + Username.getText() + "'");

            if (result.next()) {

                if (Password.getText().equals(result.getString("password"))) {           
                    Halaman_utama mn = new Halaman_utama();
                    mn.setVisible(true);

                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Password Salah");
                    Password.setText("");
                    Username.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Isikan informasi yang benar !");
                Username.setText("");
                Password.setText("");
                Username.requestFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Gagal masuk Aplikasi, coba nyalakan Xampp browser terlebih dahulu");
    }                                   
    }//GEN-LAST:event_loginActionPerformed

    private void btn_masukLoginRFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masukLoginRFIDActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new login_rfid().setVisible(true);
    }//GEN-LAST:event_btn_masukLoginRFIDActionPerformed

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginKeyPressed

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginActionPerformed(new ActionEvent(evt.getSource(), evt.getID(), "Key Press Login"));
        }
    }//GEN-LAST:event_PasswordKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Username.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_username.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_username.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_username.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_username.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_username().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JButton btn_CloseUsername;
    private javax.swing.JButton btn_MinimizeUsername;
    private javax.swing.JButton btn_masukLoginRFID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    // End of variables declaration//GEN-END:variables
}
